---
platform: linux
image: docker:///concourse/static-golang

params:
  S3_TESTING_ACCESS_KEY_ID:
  S3_TESTING_SECRET_ACCESS_KEY:
  S3_TESTING_SESSION_TOKEN:
  S3_TESTING_BUCKET:
  S3_VERSIONED_TESTING_BUCKET:
  S3_TESTING_REGION:
  S3_ENDPOINT:

inputs:
- name: s3-resource
  path: gopath/src/github.com/concourse/s3-resource

outputs:
- name: built-resource

run:
  path: gopath/src/github.com/concourse/s3-resource/scripts/ci
