#!/bin/bash

set -e

not_installed() {
  ! command -v $1 > /dev/null 2>&1
}

s3_resource_dir=$(cd $(dirname $0)/.. && pwd)

if not_installed ginkgo; then
  echo "# ginkgo is not installed! run the following command:"
  echo "    go install github.com/onsi/ginkgo/ginkgo"
  exit 1
fi

cd $s3_resource_dir

counterfeiter -o fakes/fake_s3client.go .  S3Client

ginkgo -r -p -skipPackage integration
