---
jobs:
- name: push-s3-resource
  plan:
  - get: s3-resource
    trigger: true
  - put: docker-image-repo
    params:
      build: s3-resource
      dockerfile: s3-resource/dockerfiles/alpine/Dockerfile

resources:
- name: s3-resource
  type: git
  source:
    uri: ((s3-resource-git-url))
    branch: ((s3-resource-git-branch))
    commit_verification_keys: ((cloud-gov-pgp-keys))

- name: docker-image-repo
  type: docker-image
  source:
    email: ((docker-email))
    username: ((docker-username))
    password: ((docker-password))
    repository: ((docker-repository))
